services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habit_db
    expose:
      - "5432"
    command: postgres -c shared_buffers=24MB -c max_connections=20
    volumes:
      - pg_data:/var/lib/postgresql/data
    mem_limit: 150m

  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/habit_db"
    depends_on:
      - db
    mem_limit: 150m

volumes:
  pg_data:
