version: '3.8'

services:
  db:
    # Используем alpine-версию, она весит ~100МБ вместо ~350МБ
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habit_db
    # Убираем проброс портов "5432:5432" наружу
    expose:
      - "5432"
    
    # Жесткое ограничение памяти для Docker
    deploy:
      resources:
        limits:
          memory: 100M
    
    # Тонкая настройка самого Postgres под малый объем ОЗУ
    command: >
      postgres 
      -c shared_buffers=24MB 
      -c max_connections=20 
      -c work_mem=2MB

    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Обрати внимание: вместо localhost пишем имя сервиса "db"
      DATABASE_URL: "postgresql://user:password@db:5432/habit_db"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 150M

volumes:
  pg_data:
